# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a2618392eac202d83c24457c9a84d8c3594ec2a3cb2ae1deea803e49255f6cbe6356ff073dc492ef307aab3d9aa643c109e6b46741cc13e9ab024389785d3d7

test:
  secret_key_base: a723ce6b1299def23adc9b7a00314853e54d8d5d59852e4814628aa488a3cd631aace6cab2109cfa10196c06509569dc537cb96471cf29bd7d7eec6654967e5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
